package library_management;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class borrow_return extends javax.swing.JFrame {
    public borrow_return() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JT3 = new javax.swing.JTextField();
        JT1 = new javax.swing.JTextField();
        JT2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Reader number:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 89, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Book Author:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 173, -1, -1));

        jButton2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jButton2.setText("Borrow");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Book name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        JT3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jPanel2.add(JT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 320, -1));

        JT1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        JT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT1ActionPerformed(evt);
            }
        });
        jPanel2.add(JT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 99, 320, -1));

        JT2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jPanel2.add(JT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 320, -1));

        jButton4.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jButton4.setText("return");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        jButton5.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jButton5.setText("Back");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 670));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTO/微信图片_20190509100924.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
       this.dispose();
        welcome welcome = new welcome();
        welcome.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Connection con=null;
        PreparedStatement pst = null;
        ResultSet rs=null;
        String a=null;
        try {
            con = (Connection) new database().getConnection();
            String sql = "update book set whether_to_borrow='yes' where author=? and book_name=?;";
            pst = (PreparedStatement) con.prepareStatement(sql);
            pst.setString(1, JT2.getText());
            pst.setString(2, JT3.getText());
            pst.execute();
            JOptionPane.showMessageDialog(this, "You have borrowed this book successfully!");
            sql = "select * from book where author=? and book_name=?;";
            pst = (PreparedStatement) con.prepareStatement(sql);
            pst.setString(1, JT2.getText());
            pst.setString(2, JT3.getText());
            rs=(ResultSet) pst.executeQuery();
            while(rs.next()){
                a=rs.getString(1);
            }
            sql="insert into table_borrowbook values(?,?,?,?)";
            pst=(PreparedStatement) con.prepareStatement(sql);
            pst.setString(1, a);
            pst.setInt(2, Integer.parseInt(JT1.getText()));
            Date date=new Date();
            int y=date.getYear();
            int m=date.getMonth();
            int d=date.getDate();
            java.sql.Date time=new java.sql.Date(date.getTime());
            pst.setDate(3,time);
            Date date1=new Date(y,m+1,d);
            time=new java.sql.Date(date1.getTime());
            pst.setDate(4, time);
            pst.execute();

        } catch (Exception ex) {
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void JT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT1ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        Connection con;
        PreparedStatement pst;
        String a=null;
        try {
            con = (Connection) new database().getConnection();
            String sql = "update book set whether_to_borrow='no' where author=? and book_name=?;";
            pst = (PreparedStatement) con.prepareStatement(sql);
            pst.setString(1, JT2.getText());
            pst.setString(2, JT3.getText());
            pst.execute();
            JOptionPane.showMessageDialog(this, "You have returned this book successfully!");
            sql="delete from table_borrowbook where reader_number = ?";
            pst=(PreparedStatement) con.prepareStatement(sql);
            pst.setInt(1,Integer.parseInt(JT1.getText()));
            pst.execute();
    }catch (Exception ex) {
            System.out.println(ex);
        }
        
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(borrow_return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(borrow_return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(borrow_return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(borrow_return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new borrow_return().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JT1;
    private javax.swing.JTextField JT2;
    private javax.swing.JTextField JT3;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
